version: 2
aliases:
  - &post_build
    name: Trigger downstream builds
    command: |
      echo 'export CIRCLE_API_TOKEN="$CIRCLE_API_USER_TOKEN"' >> $BASH_ENV
      /tools/downstream_single_trigger.sh "gh/entur/netex-protobuf" "master"

  - &sonar-scan
    command: |
      mvn sonar:sonar -s /tools/m2/settings.xml \
        -Dsonar.projectKey=${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.organization=enturas-github \
        -Dsonar.projectName=${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${ENTUR_SONAR_PASSWORD}

  - &release
    name: Release
    command: |
      if [ "$(git log -1 --pretty=%B)" == "Start release" ]
      then
        echo "Start release"
        mvn versions:use-releases
        SNAPSHOT_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.6.0:exec)
        TAG_VERSION="${SNAPSHOT_VERSION/-SNAPSHOT/}"
        echo "Release version $TAG_VERSION"
        mvn unleash:perform -B
        git checkout master
        git fetch --tags origin
        git merge $TAG_VERSION
        git push origin master
      else
        echo "Skipping release"
      fi

jobs:
  test:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-dependencies-{{ checksum "pom.xml" }}-deploy
            - cache-dependencies-{{ checksum "pom.xml" }}
            - cache-dependencies-static
      - run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -U -s /tools/m2/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: cache-dependencies-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: cache-dependencies-static
      # Cannot use -o because of snapshot dependencies. Using deploy &  -Dmaven.deploy.skip=true to download ALL necessary dependencies
      - run: mvn deploy -s /tools/m2/settings.xml  -Dmaven.deploy.skip=true
      - persist_to_workspace:
          root: ../
          paths:
            - project
            - .m2
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  deploy-artifactory:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - attach_workspace:
          at: ../
      - run: mvn deploy -s /tools/m2/settings.xml -DskipTests -Dspotless.check.skip=true
      - run: *post_build
      - save_cache:
          paths:
            - ~/.m2
          key: cache-dependencies-{{ checksum "pom.xml" }}-deploy

  sonar:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      #      - checkout
      - attach_workspace:
          at: ../
      - run: *sonar-scan

  release:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      #      - checkout
      - attach_workspace:
          at: ../
      - run: *release

workflows:
  version: 2
  nightly-sonar-analysis:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test:
          context: org-carbon
      - sonar:
          context: org-carbon
          requires:
            - test
  build_test_deploy:
    jobs:
      - test:
          context: org-carbon
      - deploy-artifactory:
          context: org-carbon
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          context: org-carbon
          requires:
            - test
          filters:
            branches:
              only: develop